apiVersion: v1
kind: ConfigMap
metadata:
  name: huly-config
data:
  ACCOUNTS_URL: 'http://account.huly.example/'
  COLLABORATOR_URL: 'ws://collaborator.huly.example/'
  MINIO_ENDPOINT: 'minio'
  MONGO_URL: 'mongodb://mongodb:27017'
  ELASTIC_URL: 'http://elastic:9200'
  ELASTIC_INDEX_NAME: 'huly_storage_index'