# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   labels:
#     app: workspace
#   name: workspace
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: workspace
#   template:
#     metadata:
#       labels:
#         app: workspace
#     spec:
#       containers:
#         - env:
#             - name: ACCOUNTS_URL
#               value: http://account:3000
#             - name: MINIO_ACCESS_KEY
#               value: minioadmin
#             - name: MINIO_ENDPOINT
#               value: minio
#             - name: MINIO_SECRET_KEY
#               value: minioadmin
#             - name: MODEL_ENABLED
#               value: '*'
#             - name: MONGO_URL
#               value: mongodb://mongodb:27017
#             - name: DB_URL
#               value: mongodb://mongodb:27017
#             - name: SERVER_SECRET
#               value: "{{ .Values.account.serverSecret }}"
#             - name: TRANSACTOR_URL
#               value: ws://transactor:3333;ws://localhost:3333
#             - name: NOTIFY_INBOX_ONLY
#               value: "true"
#           image: hardcoreeng/workspace:v0.6.287
#           name: workspace
#           resources:
#             limits:
#               memory: "512M"
#       restartPolicy: Always