ingress:
  domain: huly.example.com
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: haproxy
  account:
    domain: huly-account.example.com
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      kubernetes.io/ingress.class: haproxy
  collaborator:
    domain: huly-collaborator.example.com
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      kubernetes.io/ingress.class: haproxy
  transactor:
    domain: huly-transactor.example.com
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      kubernetes.io/ingress.class: haproxy
  stats:
    domain: huly-stats.example.com
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      kubernetes.io/ingress.class: haproxy
  rekoni:
    domain: huly-rekoni.example.com
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      kubernetes.io/ingress.class: haproxy
account:
  serverSecret: <change-me>