apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    kompose.cmd: kompose convert -c -o huly --controller statefulset
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: front
  name: front
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: front
  serviceName: front
  template:
    metadata:
      labels:
        io.kompose.network/huly-selfhost-default: "true"
        io.kompose.service: front
    spec:
      containers:
        - env:
            - name: ACCOUNTS_URL
              value: https://{{ .Values.ingress.account.domain }}/
            - name: CALENDAR_URL
              value: http://{{ .Values.ingress.domain }}:8095
            - name: COLLABORATOR_API_URL
              value: https://{{ .Values.ingress.collaborator.domain }}
            - name: COLLABORATOR_URL
              value: wss://{{ .Values.ingress.collaborator.domain }}
            - name: DEFAULT_LANGUAGE
              value: en
            - name: ELASTIC_URL
              value: http://elastic:9200
            - name: GMAIL_URL
              value: http://{{ .Values.ingress.domain }}:8088
            - name: LAST_NAME_FIRST
              value: "true"
            - name: MINIO_ACCESS_KEY
              value: minioadmin
            - name: MINIO_ENDPOINT
              value: minio
            - name: MINIO_SECRET_KEY
              value: minioadmin
            - name: REKONI_URL
              value: https://{{ .Values.ingress.rekoni.domain }}
            - name: SERVER_PORT
              value: "8080"
            - name: SERVER_SECRET
              value: {{ .Values.account.serverSecret }}
            - name: TELEGRAM_URL
              value: http://{{ .Values.ingress.domain }}:8086
            - name: TITLE
              value: Huly Self Hosted
            - name: UPLOAD_URL
              value: /files
            - name: MONGO_URL
              value: mongodb://mongodb:27017
            - name: STATS_URL
              value: http://stats:4900
            - name: LIVEKIT_WS
              value: wss://livekit.logicamp.tech
            - name: LOVE_ENDPOINT
              value: https://{{ .Values.ingress.love.domain }}
          image: "{{ .Values.image.registry }}/front:{{ .Values.image.tag }}"
          name: front
          ports:
            - containerPort: 8080
              hostPort: 8087
              protocol: TCP
      restartPolicy: Always
