apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    kompose.cmd: kompose convert -c -o huly --controller statefulset
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: account
  name: account
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: account
  serviceName: account
  template:
    metadata:
      labels:
        io.kompose.network/huly-selfhost-default: "true"
        io.kompose.service: account
    spec:
      containers:
        - env:
            - name: ACCOUNTS_URL
              value: http://localhost:3000
            - name: ACCOUNT_PORT
              value: "3000"
            - name: ENDPOINT_URL
              value: wss://{{ .Values.ingress.transactor.domain }}
            - name: FRONT_URL
              value: https://{{ .Values.ingress.domain }}
            - name: INIT_WORKSPACE
              value: demo-tracker
            - name: MINIO_ACCESS_KEY
              value: minioadmin
            - name: MINIO_ENDPOINT
              value: minio
            - name: MINIO_SECRET_KEY
              value: minioadmin
            - name: MODEL_ENABLED
              value: '*'
            - name: MONGO_URL
              value: mongodb://mongodb:27017
            - name: SERVER_PORT
              value: "3000"
            - name: SERVER_SECRET
              value: {{ .Values.account.serverSecret }}
            - name: TRANSACTOR_URL
              value: ws://transactor;wss://{{ .Values.ingress.transactor.domain }}/
            - name: DB_URL
              value: mongodb://mongodb:27017
          image: hardcoreeng/account:v0.6.377
          imagePullPolicy: IfNotPresent
          name: account
          ports:
            - containerPort: 3000
              hostPort: 3000
              protocol: TCP
      restartPolicy: Always
