apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -c -o huly --controller statefulset
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: elastic
  name: elastic
spec:
  clusterIP: None
  ports:
    - name: "9200"
      port: 9200
      targetPort: 9200
  selector:
    io.kompose.service: elastic
  type: ClusterIP
