apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: huly-collaborator-ingress
  annotations:
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  tls:
    - hosts:
        - {{ .Values.ingress.collaboratorDomain }}
      secretName: {{ regexReplaceAll "\\." .Values.ingress.collaboratorDomain "-" }}-tls
  rules:
    - host: {{ .Values.ingress.collaboratorDomain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: collaborator
                port:
                  number: 3078
