apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    kompose.cmd: kompose convert -c -o huly --controller statefulset
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: transactor
  name: transactor
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: transactor
  serviceName: transactor
  template:
    metadata:
      labels:
        io.kompose.network/huly-selfhost-default: "true"
        io.kompose.service: transactor
    spec:
      containers:
        - env:
            - name: ACCOUNTS_URL
              value: http://account:3000
            - name: ELASTIC_URL
              value: http://elastic:9200
            - name: FRONT_URL
              value: https://{{ .Values.ingress.domain }}
            - name: LAST_NAME_FIRST
              value: "true"
            - name: METRICS_CONSOLE
              value: "false"
            - name: METRICS_FILE
              value: metrics.txt
            - name: MINIO_ACCESS_KEY
              value: minioadmin
            - name: MINIO_ENDPOINT
              value: minio
            - name: MINIO_SECRET_KEY
              value: minioadmin
            - name: MONGO_URL
              value: mongodb://mongodb:27017
            - name: REKONI_URL
              value: http://rekoni:4004
            - name: SERVER_CURSOR_MAXTIMEMS
              value: "30000"
            - name: SERVER_PORT
              value: "3333"
            - name: SERVER_PROVIDER
              value: ws
            - name: SERVER_SECRET
              value: {{ .Values.account.serverSecret }}
            - name: ELASTIC_INDEX_NAME
              value: local_storage_index
            - name: UPLOAD_URL
              value: /files
            - name: DB_URL
              value: mongodb://mongodb:27017
            - name: FULLTEXT_URL
              value: http://fulltext:4700
            - name: STORAGE_CONFIG
              valueFrom:
                secretKeyRef:
                  name: huly-secret
                  key: STORAGE_CONFIG
          image: hardcoreeng/transactor:v0.6.377
          name: transactor
          ports:
            - containerPort: 3333
              hostPort: 3333
              protocol: TCP
      restartPolicy: Always
