apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: love
  name: huly-love
spec:
  replicas: 1
  selector:
    matchLabels:
      app: love
  template:
    metadata:
      labels:
        app: love
    spec:
      containers:
        - env:
            - name: SERVER_SECRET
              valueFrom:
                secretKeyRef:
                  name: huly-secret
                  key: SERVER_SECRET
            - name: SECRET
              valueFrom:
                secretKeyRef:
                  name: huly-secret
                  key: SERVER_SECRET
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: huly-config
                  key: MONGO_URL
            - name: MONGO_URL
              valueFrom:
                configMapKeyRef:
                  name: huly-config
                  key: MONGO_URL
            - name: FULLTEXT_DB_URL
              valueFrom:
                configMapKeyRef:
                  name: huly-config
                  key: ELASTIC_URL
            - name: ELASTIC_INDEX_NAME
              valueFrom:
                configMapKeyRef:
                  name: huly-config
                  key: ELASTIC_INDEX_NAME
            - name: STORAGE_CONFIG
              valueFrom:
                secretKeyRef:
                  name: huly-secret
                  key: STORAGE_CONFIG
            - name: REKONI_URL
              value: http://rekoni:4004
            - name: ACCOUNTS_URL
              value: http://account
            - name: STATS_URL
              value: http://stats:4900
            - name: STORAGE_PROVIDER_NAME
              value: minio
            - name: PORT
              value: "8096"
            - name: LIVEKIT_HOST
              value: livekit.logicamp.tech
            - name: LIVEKIT_API_KEY
              value: myapikey
            - name:  LIVEKIT_API_SECRET
              value: Wie3hoongaecuku5aiCha9paesh4ba6u
          image: "{{ .Values.image.registry }}/love:{{ .Values.image.tag }}"
          name: love
          ports:
            - containerPort: 8096
              hostPort: 8096
              protocol: TCP
          resources:
            limits:
              memory: "512M"
      restartPolicy: Always
