apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -c -o huly --controller statefulset
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: front
  name: front
spec:
  clusterIP: None
  ports:
    - name: "8087"
      port: 8087
      targetPort: 8080
  selector:
    io.kompose.service: front
  type: ClusterIP
