apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: workspace
  name: workspace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workspace
  template:
    metadata:
      labels:
        app: workspace
    spec:
      containers:
        - env:
            - name: ACCOUNTS_URL
              value: http://account:3000
            - name: STATS_URL
              value: http://stats:4900
            - name: TRANSACTOR_URL
              value: ws://transactor;wss://{{ .Values.ingress.transactorDomain }}/
            - name: STORAGE_CONFIG
              valueFrom:
                secretKeyRef:
                  name: huly-secret
                  key: STORAGE_CONFIG
            - name: MODEL_ENABLED
              value: '*'
            - name: MONGO_URL
              value: mongodb://mongodb:27017
            - name: DB_URL
              value: mongodb://mongodb:27017
            - name: SERVER_SECRET
              valueFrom:
                secretKeyRef:
                  name: huly-secret
                  key: SERVER_SECRET
          image: hardcoreeng/workspace:v0.6.377
          name: workspace
          resources:
            limits:
              memory: "512M"
      restartPolicy: Always