apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -c -o huly --controller statefulset
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: collaborator
  name: collaborator
spec:
  clusterIP: None
  ports:
    - name: "3078"
      port: 3078
      targetPort: 3078
  selector:
    io.kompose.service: collaborator
  type: ClusterIP
