apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    kompose.cmd: kompose convert -c -o huly --controller statefulset
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: elastic
  name: elastic
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: elastic
  serviceName: elastic
  template:
    metadata:
      labels:
        io.kompose.network/huly-selfhost-default: "true"
        io.kompose.service: elastic
    spec:
      containers:
        - args:
            - /bin/sh
            - -c
            - |-
              ./bin/elasticsearch-plugin list | grep -q ingest-attachment || yes | ./bin/elasticsearch-plugin install --silent ingest-attachment;
              /usr/local/bin/docker-entrypoint.sh eswrapper
          env:
            - name: BITNAMI_DEBUG
              value: "true"
            - name: ELASTICSEARCH_PORT_NUMBER
              value: "9200"
            - name: ES_JAVA_OPTS
              value: -Xms1024m -Xmx1024m
            - name: discovery.type
              value: single-node
            - name: http.cors.allow-origin
              value: http://localhost:8082
            - name: http.cors.enabled
              value: "true"
          image: elasticsearch:8.13.4
          livenessProbe:
            exec:
              command:
                - curl -s http://localhost:9200/_cluster/health | grep -vq '"status":"red"'
            failureThreshold: 10
            periodSeconds: 20
          name: elastic
          ports:
            - containerPort: 9200
              hostPort: 9200
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/elasticsearch/data
              name: elastic
              subPath: elastic
      restartPolicy: Always
  volumeClaimTemplates:
    - metadata:
        labels:
          io.kompose.service: elastic
        name: elastic
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 4Gi
