apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    kompose.cmd: kompose convert -c -o huly --controller statefulset
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: front
  name: front
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: front
  serviceName: front
  template:
    metadata:
      labels:
        io.kompose.network/huly-selfhost-default: "true"
        io.kompose.service: front
    spec:
      containers:
        - env:
            - name: ACCOUNTS_URL
              value: https://{{ .Values.ingress.domain }}/accounts
            - name: CALENDAR_URL
              value: http://{{ .Values.ingress.domain }}:8095
            - name: COLLABORATOR_API_URL
              value: https://{{ .Values.ingress.collaboratorDomain }}
            - name: COLLABORATOR_URL
              value: wss://{{ .Values.ingress.collaboratorDomain }}
            - name: DEFAULT_LANGUAGE
              value: en
            - name: ELASTIC_URL
              value: http://elastic:9200
            - name: GMAIL_URL
              value: http://{{ .Values.ingress.domain }}:8088
            - name: LAST_NAME_FIRST
              value: "true"
            - name: MINIO_ACCESS_KEY
              value: minioadmin
            - name: MINIO_ENDPOINT
              value: minio
            - name: MINIO_SECRET_KEY
              value: minioadmin
            - name: REKONI_URL
              value: https://{{ .Values.ingress.domain }}/rekoni
            - name: SERVER_PORT
              value: "8080"
            - name: SERVER_SECRET
              value: secret
            - name: TELEGRAM_URL
              value: http://{{ .Values.ingress.domain }}:8086
            - name: TITLE
              value: Huly Self Hosted
            - name: TRANSACTOR_URL
              value: wss://{{ .Values.ingress.transactorDomain }}
            - name: UPLOAD_URL
              value: /files
          image: hardcoreeng/front:v0.6.221
          name: front
          ports:
            - containerPort: 8080
              hostPort: 8087
              protocol: TCP
      restartPolicy: Always
