apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: huly-ingress
  annotations:
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    # haproxy-ingress.github.io/rewrite-target: /accounts/(.*) /\1
spec:
  tls:
    - hosts:
        - {{ .Values.ingress.domain }}
      secretName: {{ regexReplaceAll "\\." .Values.ingress.domain "-" }}-tls
  rules:
    - host: {{ .Values.ingress.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: front
                port:
                  number: 8087
