apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    kompose.cmd: kompose convert -c -o huly --controller statefulset
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: rekoni
  name: rekoni
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: rekoni
  serviceName: rekoni
  template:
    metadata:
      labels:
        io.kompose.network/huly-selfhost-default: "true"
        io.kompose.service: rekoni
    spec:
      containers:
        - name: rekoni
          image: hardcoreeng/rekoni-service:v0.6.288
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4004
              hostPort: 4004
              protocol: TCP
          resources:
            limits:
              memory: "524288e3"
      restartPolicy: Always
