apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -c -o huly --controller statefulset
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: rekoni
  name: rekoni
spec:
  clusterIP: None
  ports:
    - name: "4004"
      port: 4004
      targetPort: 4004
  selector:
    io.kompose.service: rekoni
  type: ClusterIP
