apiVersion: v1
kind: Secret
metadata:
  name: huly-secret
type: Opaque
stringData:
  SERVER_SECRET: {{ .Values.account.serverSecret }}
  STORAGE_CONFIG: minio|minio?accessKey=minioadmin&secretKey=minioadmin